from room_test import Room
from hazards import Hazard, Hazards
room = Room(11, 10, 9, 5)
#room.print_room()
#room.movement("west")
earth_tile = Hazard(1,1,"earth")
water_tile = Hazard(2,2,"water")
fire_tile = Hazard(3,3,"fire")
#earth_tile.print_hazard()
#water_tile.print_hazard()
#fire_tile.print_hazard()
room_Hazards = Hazards([earth_tile, water_tile])
room_Hazards.print_hazards()
room_Hazards.add_hazard(fire_tile)
room_Hazards.print_hazards()
room_Hazards.clear_hazard(fire_tile)
room_Hazards.print_hazards()
